package edu.clothifystore.ecom.util;

public enum MenuType {
	DASHBOARD, USER_MANAGEMENT, PRODUCT_MANAGEMENT, INVENTORY_MANAGEMENT, SUPPLIER_MANAGEMENT, EMPLOYEE_MANAGEMENT, ORDER_MANAGEMENT, REPORTS, SETTINGS;
}
